# Generated by Django 5.2.6 on 2026-05-24 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the school is active'),
        ),
        migrations.AddField(
            model_name='school',
            name='on_trial',
            field=models.BooleanField(default=True, help_text='Whether the school is on trial period'),
        ),
        migrations.AddField(
            model_name='school',
            name='paid_until',
            field=models.DateTimeField(blank=True, help_text='Subscription paid until date', null=True),
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_admin', models.BooleanField(default=True)),
                ('can_manage_all_tenants', models.BooleanField(default=True)),
                ('can_view_all_data', models.BooleanField(default=True)),
                ('can_manage_system_settings', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('backup_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super Admin Profile',
                'verbose_name_plural': 'Super Admin Profiles',
            },
        ),
    ]
