# Generated by Django 5.2.6 on 2026-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_school_is_active_school_on_trial_school_paid_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_level",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary School"),
                    ("JUNIOR", "Junior School"),
                    ("SENIOR", "Senior School"),
                    ("PRIMARY_JUNIOR", "Primary + Junior School"),
                    ("JUNIOR_SENIOR", "Junior + Senior School"),
                    ("COMPREHENSIVE", "Comprehensive School"),
                    ("CBC_LEGACY_SECONDARY", "CBC + Legacy Secondary School"),
                    ("LEGACY_SECONDARY", "Legacy Secondary School"),
                ],
                default="CBC_LEGACY_SECONDARY",
                help_text="Defines the school structure: Primary, Junior, Senior, Comprehensive, or CBC + Legacy Secondary.",
                max_length=30,
            ),
        ),
    ]
