# Generated by Django 5.2.6 on 2026-05-23 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachergradingpreference',
            options={'ordering': ['-is_global', '-updated_at']},
        ),
        migrations.AddField(
            model_name='teachergradingpreference',
            name='cbe_pathway',
            field=models.ForeignKey(blank=True, help_text='Select a CBE pathway for competency-based grading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_preferences', to='digitallibrary.cbegradingpathway'),
        ),
        migrations.AddField(
            model_name='teachergradingpreference',
            name='grading_choice',
            field=models.CharField(choices=[('traditional', '📊 Traditional Grade System (Default)'), ('custom', '⚙️ My Custom Grading System'), ('cbe', '🎯 Competency-Based Education (CBE)'), ('school_default', '🏫 School Default System'), ('exam_specific', '📝 Exam Specific Grading'), ('subject_specific', '📚 Subject Specific Grading')], default='traditional', help_text='Select which grading system to use', max_length=20),
        ),
        migrations.AddField(
            model_name='teachergradingpreference',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this preference is currently active'),
        ),
        migrations.AddField(
            model_name='teachergradingpreference',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Apply this preference to all your exams and subjects'),
        ),
        migrations.AlterField(
            model_name='teachergradingpreference',
            name='custom_grading_system',
            field=models.ForeignKey(blank=True, help_text="Select a custom grading system you've created", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_preferences', to='digitallibrary.gradingsystem'),
        ),
        migrations.AlterField(
            model_name='teachergradingpreference',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grading_preferences', to='digitallibrary.exam'),
        ),
        migrations.AlterField(
            model_name='teachergradingpreference',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grading_preferences', to='digitallibrary.subject'),
        ),
        migrations.AlterField(
            model_name='teachergradingpreference',
            name='use_cbe_pathways',
            field=models.BooleanField(default=False, help_text='Legacy field - use grading_choice instead'),
        ),
        migrations.AlterField(
            model_name='teachergradingpreference',
            name='use_custom_grading',
            field=models.BooleanField(default=False, help_text='Legacy field - use grading_choice instead'),
        ),
        migrations.AddIndex(
            model_name='teachergradingpreference',
            index=models.Index(fields=['teacher', 'grading_choice'], name='digitallibr_teacher_29fb78_idx'),
        ),
        migrations.AddIndex(
            model_name='teachergradingpreference',
            index=models.Index(fields=['teacher', 'exam', 'subject'], name='digitallibr_teacher_37d42e_idx'),
        ),
        migrations.AddIndex(
            model_name='teachergradingpreference',
            index=models.Index(fields=['teacher', 'is_global'], name='digitallibr_teacher_544f04_idx'),
        ),
    ]
