# Generated by Django 5.2.6 on 2026-05-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0002_teacher_grading_preference'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='applicable_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this grading system applies to', related_name='applicable_grading_systems', to='digitallibrary.class'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='applicable_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this grading system applies to', related_name='applicable_grading_systems', to='digitallibrary.subject'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='grade_calculation_type',
            field=models.CharField(choices=[('standard', 'Standard (Higher score = Better grade)'), ('reverse', 'Reverse (Lower score = Better grade, e.g., Golf)'), ('competency', 'Competency-Based')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='is_subject_specific',
            field=models.BooleanField(default=False, help_text='Is this grading system specific to a subject?'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='max_raw_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, help_text='Maximum raw score if different from percentage', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='calculation_method',
            field=models.CharField(choices=[('percentage', 'Percentage Based'), ('points', 'Points Based'), ('weighted', 'Weighted Average'), ('competency', 'Competency Level'), ('raw_score', 'Raw Score Based')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='system_type',
            field=models.CharField(choices=[('default', 'Default System'), ('custom', 'Custom Teacher Grading'), ('cbe', 'Competency-Based Education (CBE)'), ('letter', 'Letter Grade System (A, B, C, D, E)'), ('numerical', 'Numerical Grade System (75-100, 50-74, etc.)'), ('pass_fail', 'Pass/Fail System'), ('subject_specific', 'Subject-Specific Grading')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='SubjectGradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=9)),
                ('term', models.IntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum possible score for this subject', max_digits=6)),
                ('passing_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum passing score for this subject', max_digits=5)),
                ('exam_weight', models.DecimalField(decimal_places=2, default=70.0, help_text='Weight for final exam', max_digits=5)),
                ('coursework_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Weight for coursework', max_digits=5)),
                ('practical_weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Weight for practical component', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this grading configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='digitallibrary.gradingsystem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_configs', to='digitallibrary.subject')),
            ],
            options={
                'verbose_name': 'Subject Grading Configuration',
                'verbose_name_plural': 'Subject Grading Configurations',
                'ordering': ['subject__name', '-academic_year', 'term'],
                'unique_together': {('subject', 'academic_year', 'term')},
            },
        ),
        migrations.AddField(
            model_name='teachergradingpreference',
            name='subject_grading_config',
            field=models.ForeignKey(blank=True, help_text='Select a subject-specific grading configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_preferences', to='digitallibrary.subjectgradingconfig'),
        ),
        migrations.CreateModel(
            name='TVDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='School TV', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('layout', models.CharField(choices=[('split', 'Split Screen (2 columns)'), ('grid', 'Grid Layout (4 quadrants)'), ('full', 'Full Screen'), ('sidebar', 'Main + Sidebar')], default='split', max_length=20)),
                ('theme', models.CharField(choices=[('dark', 'Dark Theme (Modern)'), ('light', 'Light Theme (Classic)'), ('school', 'School Colors')], default='dark', max_length=20)),
                ('refresh_interval', models.IntegerField(default=30, help_text='Seconds between content refresh')),
                ('display_duration', models.IntegerField(default=10, help_text='Seconds per slide')),
                ('show_clock', models.BooleanField(default=True)),
                ('show_weather', models.BooleanField(default=True)),
                ('show_news_ticker', models.BooleanField(default=True)),
                ('show_events', models.BooleanField(default=True)),
                ('show_exam_schedule', models.BooleanField(default=True)),
                ('show_noticeboard', models.BooleanField(default=True, help_text='Show announcements from noticeboard')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='tv_logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='tv_backgrounds/')),
                ('accent_color', models.CharField(default='#3b82f6', help_text='Primary brand color', max_length=7)),
                ('background_color', models.CharField(default='#0f172a', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('footer_text', models.CharField(default='ShuleHub TV - Keeping You Informed', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv_display', to='tenants.school')),
            ],
            options={
                'verbose_name': 'TV Display',
                'verbose_name_plural': 'TV Displays',
            },
        ),
        migrations.CreateModel(
            name='TVContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('announcement', '📢 Announcement'), ('event', '📅 Upcoming Event'), ('exam', '📝 Exam Schedule'), ('achievement', '🏆 Achievement'), ('quote', '💡 Quote of the Day'), ('notice', '📋 Notice Board'), ('reminder', '⏰ Reminder'), ('emergency', '🚨 Emergency Alert'), ('slide', '🖼️ Image Slide')], default='announcement', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent'), (5, 'Critical')], default=2)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tv_content/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link for more info', null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_duration', models.IntegerField(default=10, help_text='Seconds to display this content')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently')),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tv_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='digitallibrary.tvdisplay')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
