# Generated by Django 6.0.5 on 2026-05-07 18:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0002_add_class_teacher_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
