# Generated by Django 5.2.6 on 2026-05-24 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0003_gradingsystem_applicable_classes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('enrolled', 'Enrolled'), ('transferred', 'Transferred Out'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('deactivated', 'Deactivated'), ('archived', 'Archived'), ('updated', 'Information Updated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred Out'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('deactivated', 'Deactivated'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_reason',
            field=models.CharField(blank=True, choices=[('transfer', 'Transferred to Another School'), ('graduated', 'Graduated/Completed'), ('withdrawn', 'Withdrawn by Parents'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('deceased', 'Deceased'), ('other', 'Other Reason')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_reason_other',
            field=models.TextField(blank=True, help_text='Detailed reason for transfer/deactivation'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_to_school',
            field=models.CharField(blank=True, help_text='Name of school transferred to (if applicable)', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'is_active'], name='digitallibr_status_085a80_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['deleted_at'], name='digitallibr_deleted_e71808_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number', 'status'], name='digitallibr_admissi_b29f65_idx'),
        ),
        migrations.AddField(
            model_name='studentactionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentactionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='digitallibrary.student'),
        ),
        migrations.AddIndex(
            model_name='studentactionlog',
            index=models.Index(fields=['student', 'action'], name='digitallibr_student_14e943_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactionlog',
            index=models.Index(fields=['-timestamp'], name='digitallibr_timesta_1defc1_idx'),
        ),
    ]
