# Generated by Django 5.2.6 on 2026-05-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0005_superadminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperAdminProfile',
        ),
    ]
