# Generated by Django 5.2.6 on 2026-05-26 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0006_delete_superadminprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KNECCBEGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('EE1', 'Exceeding Expectations 1'), ('EE2', 'Exceeding Expectations 2'), ('ME1', 'Meeting Expectations 1'), ('ME2', 'Meeting Expectations 2'), ('AE1', 'Approaching Expectations 1'), ('AE2', 'Approaching Expectations 2'), ('BE1', 'Below Expectations 1'), ('BE2', 'Below Expectations 2')], max_length=3, unique=True)),
                ('level_name', models.CharField(max_length=50)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=0, max_digits=3)),
                ('placement', models.CharField(choices=[('national', 'National School'), ('extra_county', 'Extra-County School'), ('county', 'County School'), ('sub_county', 'Sub-County School')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KNEC CBE Grade',
                'verbose_name_plural': 'KNEC CBE Grades',
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['-exam__created_at']},
        ),
        migrations.AlterModelOptions(
            name='tvcontent',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'TV Content', 'verbose_name_plural': 'TV Content'},
        ),
        migrations.RemoveIndex(
            model_name='studentresult',
            name='digitallibr_student_ed49e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentresult',
            name='digitallibr_grade_c25467_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentresult',
            name='digitallibr_compete_69c5ba_idx',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='competency_level',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='grade_remark',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='grading_system_used',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='performance_trend',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='teacher_comment',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='entered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvcontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='tvdisplay',
            name='weather_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tvdisplay',
            name='weather_location',
            field=models.CharField(blank=True, help_text='City name for weather (e.g., Nairobi)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tvdisplay',
            name='weather_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitallibrary.subject'),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image/photo (JPEG, PNG, GIF, WebP) - Max 5MB', null=True, upload_to='tv_content/%Y/%m/%d/', verbose_name='Upload Photo/Image'),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show prominently in hero section'),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='message',
            field=models.TextField(blank=True, help_text='Content message (optional for image slides)', null=True),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='priority',
            field=models.IntegerField(choices=[(1, '🟢 Low'), (2, '🔵 Normal'), (3, '🟡 High'), (4, '🟠 Urgent'), (5, '🔴 Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='tvcontent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitallibrary.kneccbegrade'),
        ),
    ]
