# Generated by Django 5.2.6 on 2026-05-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0007_kneccbegrade_alter_studentresult_options_and_more'),
    ]

    operations = [
    ]
