# Generated by Django 5.2.6 on 2026-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0009_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
    ]
