# Generated by Django 5.2.6 on 2026-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitallibrary", "0011_feedback_table_exists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tvdisplay",
            name="school",
        ),
        migrations.AddField(
            model_name="tvdisplay",
            name="school_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
