# Generated by Django 5.2.6 on 2026-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitallibrary", "0012_remove_tvdisplay_school_tvdisplay_school_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="upi_number",
            field=models.CharField(
                blank=True,
                help_text="Optional UPI/NEMIS number. Leave blank if not available.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
