# Generated by Django 5.2.6 on 2026-06-14 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0012_remove_tvdisplay_school_tvdisplay_school_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, editable=False, max_length=63)),
                ('tenant_name', models.CharField(editable=False, max_length=200)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('pre_restore', 'Pre-restore Safety Backup')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('restoring', 'Restoring'), ('restored', 'Restored')], db_index=True, default='pending', max_length=20)),
                ('backup_file', models.FileField(blank=True, max_length=500, null=True, upload_to='tenant_backups/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Backup file size in bytes')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum used to verify backup integrity', max_length=64)),
                ('database_format', models.CharField(default='postgres_custom', help_text='For example: postgres_custom or json', max_length=20)),
                ('includes_media', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tenant Backup',
                'verbose_name_plural': 'Tenant Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tvdisplay',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'TV Display', 'verbose_name_plural': 'TV Displays'},
        ),
        migrations.AlterField(
            model_name='feebalance',
            name='historical_notes',
            field=models.TextField(blank=True, help_text='Notes about historical arrears', null=True),
        ),
        migrations.AlterField(
            model_name='feebalance',
            name='previous_academic_year',
            field=models.CharField(blank=True, help_text='Academic year when arrears originated', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='feebalance',
            name='previous_class',
            field=models.ForeignKey(blank=True, help_text='Class from which the arrears originated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_balances', to='digitallibrary.class'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql=(
                'DROP INDEX IF EXISTS '
                '"digitallibrary_tvdisplay_school_id_9087f48a";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='tvdisplay',
            name='school_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Optional public tenant School ID for reference only. Not a foreign key.', null=True),
        ),
        migrations.AlterField(
            model_name='tvdisplay',
            name='weather_location',
            field=models.CharField(blank=True, help_text='City name for weather, e.g. Nairobi', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='digitallibr_student_1f9b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='digitallibr_payment_cde407_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_number'], name='digitallibr_receipt_649189_idx'),
        ),
        migrations.AddField(
            model_name='tenantbackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantbackup',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_tenant_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantbackup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_backups', to='digitallibrary.school'),
        ),
        migrations.AddField(
            model_name='tenantrestorelog',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_logs', to='digitallibrary.tenantbackup'),
        ),
        migrations.AddField(
            model_name='tenantrestorelog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_restore_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantrestorelog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_logs', to='digitallibrary.school'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['tenant_schema', '-created_at'], name='digitallibr_tenant__e61e57_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['school', '-created_at'], name='digitallibr_school__8c69c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['status'], name='digitallibr_status_dad886_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['backup_type'], name='digitallibr_backup__509dba_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrestorelog',
            index=models.Index(fields=['tenant_schema', '-started_at'], name='digitallibr_tenant__86ced6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrestorelog',
            index=models.Index(fields=['status'], name='digitallibr_status_efd563_idx'),
        ),
    ]
