# Generated by Django 5.2.6 on 2026-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitallibrary", "0020_merge_student_upi_and_repair_grading"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="class",
            name="curriculum",
            field=models.CharField(
                choices=[("CBC", "CBC"), ("LEGACY_844", "8-4-4 Legacy")],
                db_index=True,
                default="CBC",
                help_text="CBC or 8-4-4 Legacy.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="is_legacy",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for legacy 8-4-4 classes such as Form 3 and Form 4.",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="level",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("JUNIOR", "Junior"),
                    ("SENIOR", "Senior"),
                    ("LEGACY_SECONDARY", "Legacy Secondary"),
                ],
                db_index=True,
                default="SENIOR",
                help_text="Primary, Junior, Senior, or Legacy Secondary.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="requires_pathway",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Only Grade 10, Grade 11 and Grade 12 should require pathway selection.",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Used to order Grade 1 to Grade 12 and Form 3 to Form 4.",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="pathway",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not applicable / Old system"),
                    ("arts_sports", "Arts & Sports Science"),
                    ("social_sciences", "Social Sciences"),
                    ("stem", "Science, Technology, Engineering & Mathematics"),
                ],
                help_text="Optional. Required only for Grade 10, Grade 11 and Grade 12. Leave blank for Grade 1–9 and legacy Form 3–4 students.",
                max_length=30,
                null=True,
            ),
        ),
    ]
