# Generated by Django 5.2.6 on 2026-06-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digitallibrary",
            "0021_alter_class_options_class_curriculum_class_is_legacy_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="digitallibrary.class",
                    ),
                ),
            ],
            options={
                "ordering": ["school_class__sort_order", "school_class__name", "name"],
                "unique_together": {("school_class", "name")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="digitallibrary.classstream",
            ),
        ),
    ]
