# Generated by Django 5.2.6 on 2026-06-23 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "digitallibrary",
            "0021_alter_class_options_class_curriculum_class_is_legacy_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LAB", "Laboratory"),
                            ("LIBRARY", "Library"),
                            ("HALL", "Hall"),
                            ("FIELD", "Field / Sports Ground"),
                            ("ICT", "ICT Room"),
                            ("WORKSHOP", "Workshop"),
                            ("OTHER", "Other"),
                        ],
                        default="CLASSROOM",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimetableTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Main Timetable", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_on_tv", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_timetable_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimetablePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("LESSON", "Lesson"),
                            ("BREAK", "Break"),
                            ("LUNCH", "Lunch"),
                            ("ASSEMBLY", "Assembly"),
                            ("GAMES", "Games"),
                            ("CLUB", "Club"),
                            ("PREP", "Prep"),
                            ("EXAM", "Exam"),
                            ("REMEDIAL", "Remedial"),
                            ("OTHER", "Other"),
                        ],
                        default="LESSON",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_teaching_period", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="timetable.timetabletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimetableDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="timetable.timetabletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("template", "day")},
            },
        ),
        migrations.CreateModel(
            name="TimetableTVSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_current_lessons", models.BooleanField(default=True)),
                ("show_next_lessons", models.BooleanField(default=True)),
                ("show_free_classes", models.BooleanField(default=True)),
                ("show_teacher_names", models.BooleanField(default=True)),
                ("show_rooms", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=30)),
                (
                    "title",
                    models.CharField(
                        default="Current Lessons Going On", max_length=100
                    ),
                ),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tv_setting",
                        to="timetable.timetabletemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_activity",
                    models.CharField(
                        blank=True,
                        help_text="Use this for Assembly, Games, Clubs, Remedial, Prep, etc.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_on_tv", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="digitallibrary.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_timetable_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="timetable.timetableday",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="digitallibrary.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="timetable.timetableperiod",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="timetable.timetableroom",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="timetable.timetabletemplate",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "day__sort_order",
                    "period__sort_order",
                    "class_group__name",
                ],
                "unique_together": {("template", "day", "period", "class_group")},
            },
        ),
    ]
